#!/usr/bin/env python3
"""
build-shell.py — keep the header, nav and footer identical across every page.

Edit the templates in tools/shell/, run this, and every hand-authored page is
re-rendered with the new shell. The output is plain static HTML: nothing is
fetched at runtime, so the hero is in the initial markup and pages work with
JavaScript disabled.

    python3 tools/build-shell.py           # rewrite pages that changed
    python3 tools/build-shell.py --check   # report what would change, write nothing

What is preserved from each existing page:
  - its <title>
  - everything inside <main class="page" id="page">…</main>
  - its own <link>/<script> tags (anything that isn't a shell asset)

Everything else is regenerated. Pages generated by build-stories.py are skipped
— they are rendered from data and already use the same base template.
"""

import re
import sys
from pathlib import Path

from markupsafe import Markup

from buildlib import (GENERATED_MARKER, ROOT, make_env, root_prefix,
                      section_for, write_if_changed)

# Assets owned by the shell. Anything else in a page's head or body is treated
# as page-specific and carried over untouched.
SHELL_ASSETS = ("css/styles.css", "js/script.js", "js/router.js",
                "fonts.googleapis.com", "fonts.gstatic.com",
                "assets/hero-")


def is_shell_asset(tag: str) -> bool:
    return any(marker in tag for marker in SHELL_ASSETS)


def extract(html: str, rel: Path):
    """Pull the parts of an existing page that must survive the rewrite."""
    title_match = re.search(r"<title>(.*?)</title>", html, re.S)
    title = title_match.group(1).strip() if title_match else "Burrito Rumbero"

    start = html.find('<main class="page" id="page">')
    end = html.rfind("</main>")
    if start == -1 or end == -1:
        raise SystemExit(f'{rel}: no <main class="page" id="page"> block found')
    content = html[html.index(">", start) + 1:end].strip("\n").rstrip()

    head_part = html[:html.find("</head>")]
    page_head = [t.strip() for t in re.findall(r"[ \t]*<link\b[^>]*>", head_part)
                 if not is_shell_asset(t)]

    body_part = html[html.find("</main>"):]
    page_scripts = [t.strip() for t in re.findall(r"[ \t]*<script\b[^>]*></script>", body_part)
                    if not is_shell_asset(t)]

    return title, content, page_head, page_scripts


def build(check_only: bool = False) -> int:
    env = make_env()
    template = env.get_template("page.html.j2")

    pages = sorted(p for p in ROOT.rglob("index.html")
                   if "tools" not in p.relative_to(ROOT).parts)
    changed = skipped = 0

    for page in pages:
        rel = page.relative_to(ROOT)
        original = page.read_text(encoding="utf-8")

        if original.startswith(GENERATED_MARKER):
            skipped += 1
            continue

        title, content, page_head, page_scripts = extract(original, rel)

        # These three are existing HTML lifted out of the page, not user data,
        # so they bypass autoescaping. Everything else the templates render
        # (titles, story fields) is escaped normally.
        rendered = template.render(
            title=title,
            root=root_prefix(rel),
            section=section_for(rel),
            content=Markup(content),
            head_extra=Markup("\n" + "\n".join(f"  {t}" for t in page_head)) if page_head else Markup(""),
            scripts=Markup("\n" + "\n".join(f"  {t}" for t in page_scripts)) if page_scripts else Markup(""),
        )

        if rendered == original:
            continue

        changed += 1
        print(f"  {'~' if check_only else '→'} {rel}  ({section_for(rel)})")
        if not check_only:
            write_if_changed(page, rendered)

    verb = "would change" if check_only else "rewritten"
    print(f"\n{len(pages)} pages: {changed} {verb}, "
          f"{skipped} generated by build-stories.py (skipped).")
    return changed


if __name__ == "__main__":
    sys.exit(0 if build(check_only="--check" in sys.argv) >= 0 else 1)
