"""Shared Jinja setup for the build scripts.

Both builders render the same base template, so a page generated by
build-stories.py and a page stamped by build-shell.py come out identical.
"""

from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "tools" / "shell"

# Written into every generated story/chapter page so build-shell.py knows to
# leave them alone — they are rendered from data, not hand-authored.
GENERATED_MARKER = "<!-- generated by build-stories.py -->"

SECTIONS = ("home", "stories", "gallery", "links", "about")


def make_env() -> Environment:
    return Environment(
        loader=FileSystemLoader(TEMPLATES),
        autoescape=True,       # titles and synopses are escaped automatically
        undefined=StrictUndefined,  # a typo'd variable fails loudly instead of rendering ""
        trim_blocks=False,
        lstrip_blocks=False,
        keep_trailing_newline=True,
    )


def root_prefix(rel: Path) -> str:
    """index.html -> ''  |  stories/1kie/index.html -> '../../'"""
    return "../" * (len(rel.parts) - 1)


def section_for(rel: Path) -> str:
    """stories/1kie/chapters/c001/index.html -> 'stories'; index.html -> 'home'."""
    return rel.parts[0] if len(rel.parts) > 1 else "home"


def write_if_changed(path: Path, text: str) -> bool:
    """Only touch files whose content actually differs."""
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True
