"""Shared Jinja setup for the build scripts.

Both builders render the same base template, so a page generated by
build-stories.py and a page stamped by build-shell.py come out identical.
"""

import re
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, StrictUndefined

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES = ROOT / "tools" / "shell"

# Written into every generated page so build-shell.py knows to leave them
# alone — they are rendered from data, not hand-authored.
GENERATED_MARKER = "<!-- generated by build-stories.py -->"
GALLERY_MARKER = "<!-- generated by build-gallery.py -->"
GENERATED_PREFIX = "<!-- generated by build-"

SECTIONS = ("home", "stories", "gallery", "links", "about")

COVER_WIDTHS = (800, 1200, 1600)
COVER_SIZES = "(max-width: 900px) 100vw, 900px"
# Preference order: the browser takes the first format it supports.
COVER_FORMATS = (("avif", "image/avif"), ("webp", "image/webp"), ("jpg", "image/jpeg"))


def cover_data(content_dir: Path) -> dict:
    """Describe which assets/cover-* variants exist. Templates decide markup.

    Never advertise a format that isn't on disk: if a browser matches a
    <source> and the file 404s, it shows a broken image rather than falling
    through to the next one.
    """
    assets = content_dir / "assets"
    available = []
    for ext, mime in COVER_FORMATS:
        widths = [w for w in COVER_WIDTHS if (assets / f"cover-{w}.{ext}").is_file()]
        if widths:
            srcset = ", ".join(f"assets/cover-{w}.{ext} {w}w" for w in widths)
            available.append({"ext": ext, "mime": mime, "widths": widths, "srcset": srcset})

    data = {"sizes": COVER_SIZES, "sources": [], "img": None, "preload": None}

    if not available:
        print("    ! no assets/cover-*.{avif,webp,jpg} found")
        return data

    last = available[-1]
    data["sources"] = available[:-1]
    data["img"] = {
        "src": f"assets/cover-{last['widths'][len(last['widths']) // 2]}.{last['ext']}",
        "srcset": last["srcset"],
    }
    data["preload"] = {"mime": available[0]["mime"], "srcset": available[0]["srcset"]}
    return data


def make_env() -> Environment:
    return Environment(
        loader=FileSystemLoader(TEMPLATES),
        autoescape=True,       # titles and synopses are escaped automatically
        undefined=StrictUndefined,  # a typo'd variable fails loudly instead of rendering ""
        trim_blocks=False,
        lstrip_blocks=False,
        keep_trailing_newline=True,
    )


def root_prefix(rel: Path) -> str:
    """index.html -> ''  |  stories/1kie/index.html -> '../../'"""
    return "../" * (len(rel.parts) - 1)


def section_for(rel: Path) -> str:
    """stories/1kie/chapters/c001/index.html -> 'stories'; index.html -> 'home'."""
    return rel.parts[0] if len(rel.parts) > 1 else "home"


def write_if_changed(path: Path, text: str) -> bool:
    """Only touch files whose content actually differs."""
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return True


# Most-optimized first. When the same page exists in several formats, the
# first match is the one served and the rest are ignored.
PAGE_EXT_PREFERENCE = (".avif", ".webp", ".jpg", ".jpeg", ".png")


def pick_page_files(pages_dir: Path) -> dict:
    """One file per page number: {"1": Path, "2": Path, ...}.

    A comic page is identified by its numeric stem, not its filename — 1.png
    and 1.webp are the *same page* in two formats, not two pages. Without this
    dedupe, a half-finished PNG→WebP conversion makes every converted page
    appear twice in the reader.

    Preference order is most-optimized first (see PAGE_EXT_PREFERENCE), so if
    both 1.webp and 1.png exist, the WebP is used everywhere — reader
    fallback, thumbnail source, variant source — and the PNG is ignored with
    a warning telling you it can be deleted.
    """
    groups = {}
    for f in sorted(pages_dir.iterdir()):
        if not f.is_file() or f.suffix.lower() not in PAGE_EXT_PREFERENCE:
            continue
        if not re.fullmatch(r"\d+", f.stem):
            print(f"    ! pages/{f.name}: name isn't a number, skipped")
            continue
        groups.setdefault(f.stem, []).append(f)

    chosen = {}
    for stem, files in groups.items():
        files.sort(key=lambda f: PAGE_EXT_PREFERENCE.index(f.suffix.lower()))
        chosen[stem] = files[0]
        if len(files) > 1:
            ignored = ", ".join(f.name for f in files[1:])
            print(f"    ! page {stem} exists in {len(files)} formats — using "
                  f"{files[0].name}; delete the rest ({ignored})")
    return chosen
